name: vars_secrets_contexts

on:
    workflow_dispatch:

env:
    cloud: google-cloud

jobs: 
    greetings_jobs:
        runs-on: ubuntu-latest
        env: 
            level_stage: stage 
        steps: 
            - uses: actions/checkout@v4

            -   name: greetings
                run: echo "Hello user!!! $cloud, $level_stage, $level_step with project ${{vars.PROJECT_ID}}"
                env:
                    level_step: step

